//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Fluenttextcanvas_prefab
    {
        public const string BundleName = "fluenttextcanvas_prefab";
        public const string FLUENTTEXTCANVAS = "fluenttextcanvas";
    }
    public class Geli_wav
    {
        public const string BundleName = "geli_wav";
        public const string GELI = "geli";
    }
    public class Guangbo_mp3
    {
        public const string BundleName = "guangbo_mp3";
        public const string GUANGBO = "guangbo";
    }
    public class Human_prefab
    {
        public const string BundleName = "human_prefab";
        public const string HUMAN = "human";
    }
    public class Intense_ogg
    {
        public const string BundleName = "intense_ogg";
        public const string INTENSE = "intense";
    }
    public class Rap_mp3
    {
        public const string BundleName = "rap_mp3";
        public const string RAP = "rap";
    }
    public class Simplecitizens_biker_black_prefab
    {
        public const string BundleName = "simplecitizens_biker_black_prefab";
        public const string SIMPLECITIZENS_BIKER_BLACK = "simplecitizens_biker_black";
    }
    public class Simplecitizens_biker_brown_prefab
    {
        public const string BundleName = "simplecitizens_biker_brown_prefab";
        public const string SIMPLECITIZENS_BIKER_BROWN = "simplecitizens_biker_brown";
    }
    public class Simplecitizens_biker_white_prefab
    {
        public const string BundleName = "simplecitizens_biker_white_prefab";
        public const string SIMPLECITIZENS_BIKER_WHITE = "simplecitizens_biker_white";
    }
    public class Simplecitizens_cheerleader_black_prefab
    {
        public const string BundleName = "simplecitizens_cheerleader_black_prefab";
        public const string SIMPLECITIZENS_CHEERLEADER_BLACK = "simplecitizens_cheerleader_black";
    }
    public class Simplecitizens_cheerleader_brown_prefab
    {
        public const string BundleName = "simplecitizens_cheerleader_brown_prefab";
        public const string SIMPLECITIZENS_CHEERLEADER_BROWN = "simplecitizens_cheerleader_brown";
    }
    public class Simplecitizens_cheerleader_white_prefab
    {
        public const string BundleName = "simplecitizens_cheerleader_white_prefab";
        public const string SIMPLECITIZENS_CHEERLEADER_WHITE = "simplecitizens_cheerleader_white";
    }
    public class Simplecitizens_clown_black_prefab
    {
        public const string BundleName = "simplecitizens_clown_black_prefab";
        public const string SIMPLECITIZENS_CLOWN_BLACK = "simplecitizens_clown_black";
    }
    public class Simplecitizens_clown_brown_prefab
    {
        public const string BundleName = "simplecitizens_clown_brown_prefab";
        public const string SIMPLECITIZENS_CLOWN_BROWN = "simplecitizens_clown_brown";
    }
    public class Simplecitizens_clown_white_prefab
    {
        public const string BundleName = "simplecitizens_clown_white_prefab";
        public const string SIMPLECITIZENS_CLOWN_WHITE = "simplecitizens_clown_white";
    }
    public class Simplecitizens_emo_black_prefab
    {
        public const string BundleName = "simplecitizens_emo_black_prefab";
        public const string SIMPLECITIZENS_EMO_BLACK = "simplecitizens_emo_black";
    }
    public class Simplecitizens_emo_brown_prefab
    {
        public const string BundleName = "simplecitizens_emo_brown_prefab";
        public const string SIMPLECITIZENS_EMO_BROWN = "simplecitizens_emo_brown";
    }
    public class Simplecitizens_emo_white_prefab
    {
        public const string BundleName = "simplecitizens_emo_white_prefab";
        public const string SIMPLECITIZENS_EMO_WHITE = "simplecitizens_emo_white";
    }
    public class Simplecitizens_footballer_black_prefab
    {
        public const string BundleName = "simplecitizens_footballer_black_prefab";
        public const string SIMPLECITIZENS_FOOTBALLER_BLACK = "simplecitizens_footballer_black";
    }
    public class Simplecitizens_footballer_brown_prefab
    {
        public const string BundleName = "simplecitizens_footballer_brown_prefab";
        public const string SIMPLECITIZENS_FOOTBALLER_BROWN = "simplecitizens_footballer_brown";
    }
    public class Simplecitizens_footballer_white_prefab
    {
        public const string BundleName = "simplecitizens_footballer_white_prefab";
        public const string SIMPLECITIZENS_FOOTBALLER_WHITE = "simplecitizens_footballer_white";
    }
    public class Simplecitizens_grandma_black_prefab
    {
        public const string BundleName = "simplecitizens_grandma_black_prefab";
        public const string SIMPLECITIZENS_GRANDMA_BLACK = "simplecitizens_grandma_black";
    }
    public class Simplecitizens_grandma_brown_prefab
    {
        public const string BundleName = "simplecitizens_grandma_brown_prefab";
        public const string SIMPLECITIZENS_GRANDMA_BROWN = "simplecitizens_grandma_brown";
    }
    public class Simplecitizens_grandma_white_prefab
    {
        public const string BundleName = "simplecitizens_grandma_white_prefab";
        public const string SIMPLECITIZENS_GRANDMA_WHITE = "simplecitizens_grandma_white";
    }
    public class Simplecitizens_grandpa_black_prefab
    {
        public const string BundleName = "simplecitizens_grandpa_black_prefab";
        public const string SIMPLECITIZENS_GRANDPA_BLACK = "simplecitizens_grandpa_black";
    }
    public class Simplecitizens_grandpa_brown_prefab
    {
        public const string BundleName = "simplecitizens_grandpa_brown_prefab";
        public const string SIMPLECITIZENS_GRANDPA_BROWN = "simplecitizens_grandpa_brown";
    }
    public class Simplecitizens_grandpa_white_prefab
    {
        public const string BundleName = "simplecitizens_grandpa_white_prefab";
        public const string SIMPLECITIZENS_GRANDPA_WHITE = "simplecitizens_grandpa_white";
    }
    public class Simplecitizens_hippie_black_prefab
    {
        public const string BundleName = "simplecitizens_hippie_black_prefab";
        public const string SIMPLECITIZENS_HIPPIE_BLACK = "simplecitizens_hippie_black";
    }
    public class Simplecitizens_hippie_brown_prefab
    {
        public const string BundleName = "simplecitizens_hippie_brown_prefab";
        public const string SIMPLECITIZENS_HIPPIE_BROWN = "simplecitizens_hippie_brown";
    }
    public class Simplecitizens_hippie_white_prefab
    {
        public const string BundleName = "simplecitizens_hippie_white_prefab";
        public const string SIMPLECITIZENS_HIPPIE_WHITE = "simplecitizens_hippie_white";
    }
    public class Simplecitizens_luchador_black_prefab
    {
        public const string BundleName = "simplecitizens_luchador_black_prefab";
        public const string SIMPLECITIZENS_LUCHADOR_BLACK = "simplecitizens_luchador_black";
    }
    public class Simplecitizens_luchador_brown_prefab
    {
        public const string BundleName = "simplecitizens_luchador_brown_prefab";
        public const string SIMPLECITIZENS_LUCHADOR_BROWN = "simplecitizens_luchador_brown";
    }
    public class Simplecitizens_luchador_white_prefab
    {
        public const string BundleName = "simplecitizens_luchador_white_prefab";
        public const string SIMPLECITIZENS_LUCHADOR_WHITE = "simplecitizens_luchador_white";
    }
    public class Simplecitizens_mountie_black_prefab
    {
        public const string BundleName = "simplecitizens_mountie_black_prefab";
        public const string SIMPLECITIZENS_MOUNTIE_BLACK = "simplecitizens_mountie_black";
    }
    public class Simplecitizens_mountie_brown_prefab
    {
        public const string BundleName = "simplecitizens_mountie_brown_prefab";
        public const string SIMPLECITIZENS_MOUNTIE_BROWN = "simplecitizens_mountie_brown";
    }
    public class Simplecitizens_mountie_white_prefab
    {
        public const string BundleName = "simplecitizens_mountie_white_prefab";
        public const string SIMPLECITIZENS_MOUNTIE_WHITE = "simplecitizens_mountie_white";
    }
    public class Simplecitizens_nerd_black_prefab
    {
        public const string BundleName = "simplecitizens_nerd_black_prefab";
        public const string SIMPLECITIZENS_NERD_BLACK = "simplecitizens_nerd_black";
    }
    public class Simplecitizens_nerd_brown_prefab
    {
        public const string BundleName = "simplecitizens_nerd_brown_prefab";
        public const string SIMPLECITIZENS_NERD_BROWN = "simplecitizens_nerd_brown";
    }
    public class Simplecitizens_nerd_white_prefab
    {
        public const string BundleName = "simplecitizens_nerd_white_prefab";
        public const string SIMPLECITIZENS_NERD_WHITE = "simplecitizens_nerd_white";
    }
    public class Simplecitizens_prisoner_black_prefab
    {
        public const string BundleName = "simplecitizens_prisoner_black_prefab";
        public const string SIMPLECITIZENS_PRISONER_BLACK = "simplecitizens_prisoner_black";
    }
    public class Simplecitizens_prisoner_brown_prefab
    {
        public const string BundleName = "simplecitizens_prisoner_brown_prefab";
        public const string SIMPLECITIZENS_PRISONER_BROWN = "simplecitizens_prisoner_brown";
    }
    public class Simplecitizens_prisoner_white_prefab
    {
        public const string BundleName = "simplecitizens_prisoner_white_prefab";
        public const string SIMPLECITIZENS_PRISONER_WHITE = "simplecitizens_prisoner_white";
    }
    public class Simplecitizens_racer_black_prefab
    {
        public const string BundleName = "simplecitizens_racer_black_prefab";
        public const string SIMPLECITIZENS_RACER_BLACK = "simplecitizens_racer_black";
    }
    public class Simplecitizens_racer_brown_prefab
    {
        public const string BundleName = "simplecitizens_racer_brown_prefab";
        public const string SIMPLECITIZENS_RACER_BROWN = "simplecitizens_racer_brown";
    }
    public class Simplecitizens_racer_white_prefab
    {
        public const string BundleName = "simplecitizens_racer_white_prefab";
        public const string SIMPLECITIZENS_RACER_WHITE = "simplecitizens_racer_white";
    }
    public class Simplecitizens_runner_black_prefab
    {
        public const string BundleName = "simplecitizens_runner_black_prefab";
        public const string SIMPLECITIZENS_RUNNER_BLACK = "simplecitizens_runner_black";
    }
    public class Simplecitizens_runner_brown_prefab
    {
        public const string BundleName = "simplecitizens_runner_brown_prefab";
        public const string SIMPLECITIZENS_RUNNER_BROWN = "simplecitizens_runner_brown";
    }
    public class Simplecitizens_runner_white_prefab
    {
        public const string BundleName = "simplecitizens_runner_white_prefab";
        public const string SIMPLECITIZENS_RUNNER_WHITE = "simplecitizens_runner_white";
    }
    public class Simplecitizens_shopkeeper_black_prefab
    {
        public const string BundleName = "simplecitizens_shopkeeper_black_prefab";
        public const string SIMPLECITIZENS_SHOPKEEPER_BLACK = "simplecitizens_shopkeeper_black";
    }
    public class Simplecitizens_shopkeeper_brown_prefab
    {
        public const string BundleName = "simplecitizens_shopkeeper_brown_prefab";
        public const string SIMPLECITIZENS_SHOPKEEPER_BROWN = "simplecitizens_shopkeeper_brown";
    }
    public class Simplecitizens_shopkeeper_white_prefab
    {
        public const string BundleName = "simplecitizens_shopkeeper_white_prefab";
        public const string SIMPLECITIZENS_SHOPKEEPER_WHITE = "simplecitizens_shopkeeper_white";
    }
    public class Simplecitizens_tourist_black_prefab
    {
        public const string BundleName = "simplecitizens_tourist_black_prefab";
        public const string SIMPLECITIZENS_TOURIST_BLACK = "simplecitizens_tourist_black";
    }
    public class Simplecitizens_tourist_brown_prefab
    {
        public const string BundleName = "simplecitizens_tourist_brown_prefab";
        public const string SIMPLECITIZENS_TOURIST_BROWN = "simplecitizens_tourist_brown";
    }
    public class Simplecitizens_tourist_white_prefab
    {
        public const string BundleName = "simplecitizens_tourist_white_prefab";
        public const string SIMPLECITIZENS_TOURIST_WHITE = "simplecitizens_tourist_white";
    }
    public class Uihomepanel_prefab
    {
        public const string BundleName = "uihomepanel_prefab";
        public const string UIHOMEPANEL = "uihomepanel";
    }
}
